Adding clear option - remove results folder

diff --git a/gen_strings_files b/gen_strings_files
--- a/gen_strings_files
+++ b/gen_strings_files
@@ -2,41 +2,55 @@
 
 # gen_strings_files <programming_language> <config_file> <source_file>
 
+# define usage function
+usage(){
+	echo "ERROR: You can use clear to remove the results directory or you need to specify the programming language to use on generation, the name of the config and source files."
+	echo "usage: gen_string_files [Android | iOS] config_file source_file"
+	echo "       gen_string_files clear"
+	exit 1
+}
+
 srcFile=$3
 resultsDir="results"
-rm -rf $resultsDir
-mkdir -p $resultsDir/$1
 
-if [ "$3" == "" ]
+# Validate usage
+if [ "$#" -eq 1 ]
 then
-	echo "ERROR: You need to specify the programming language to use on generation, the name of the config and source files."
-	echo "usage: gen_string_files [Android | iOS] config_file source_file"
-else
-	while read line
-	do
-		language=$(echo $line|cut -d, -f1)
-		column=$(echo $line|cut -d, -f2)
-		# iOS 
-		if [ "$1" == "iOS" ]
-		then
-			dir="$resultsDir/$1/$language.lproj"
-			mkdir $dir
-			file="./$dir/Localizable.strings"
-			echo "$1 - $language: Generating $file ..."
-			cat $srcFile|cut -d, -f1,$column|sed 's/^/"/g'|sed 's/,/"="/g'|sed 's/$/";/g' > $file
-		# Android
-		elif [ "$1" == "Android" ]
-		then
-			dir="$resultsDir/$1/values-$language"
-			mkdir $dir
-			file="./$dir/strings.xml"
-			echo "$1 - $language: Generating $file ..."
-			echo "<?xml version="1.0" encoding="utf-8"?>" > $file
-			echo " <resources>" >> $file
-			cat $srcFile|cut -d, -f1,$column|sed 's/^/  <string name="/g'|sed 's/,/">/g'|sed 's/$/<\/string>/g' >> $file
-			echo " </resources>" >> $file
-		fi
-	done < $2
-
+	if [ "$1" == "clear" ]
+	then
+		rm -rf $resultsDir
+		exit 0
+	else
+		usage
+	fi
+elif [ "$#" -ne 3 ]
+then
+	usage
 fi
+		
+while read line
+do
+	language=$(echo $line|cut -d, -f1)
+	column=$(echo $line|cut -d, -f2)
+	# iOS 
+	if [ "$1" == "iOS" ]
+	then
+		dir="$resultsDir/$1/$language.lproj"
+		mkdir -p $dir
+		file="./$dir/Localizable.strings"
+		echo "$1 - $language: Generating $file ..."
+		cat $srcFile|cut -d, -f1,$column|sed 's/^/"/g'|sed 's/,/"="/g'|sed 's/$/";/g' > $file
+	# Android
+	elif [ "$1" == "Android" ]
+	then
+		dir="$resultsDir/$1/values-$language"
+		mkdir -p $dir
+		file="./$dir/strings.xml"
+		echo "$1 - $language: Generating $file ..."
+		echo "<?xml version="1.0" encoding="utf-8"?>" > $file
+		echo " <resources>" >> $file
+		cat $srcFile|cut -d, -f1,$column|sed 's/^/  <string name="/g'|sed 's/,/">/g'|sed 's/$/<\/string>/g' >> $file
+		echo " </resources>" >> $file
+	fi
+done < $2
 
